apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzaHViaGFtMDEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImMyaDFZbWhoYlhOM2JuUkFaMjFoYVd3dVkyOXRPbE5vZFdJeE1qTTAiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
